version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: kwasec
      MONGO_INITDB_ROOT_PASSWORD: EirmchcohV8zpo5L
    volumes:
      - mongo_data:/data/db
      - ./src/infrastructure/database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "kwasecpass"]
    volumes:
      - redis_data:/data


volumes:
  mongo_data:
  redis_data:
